### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by bjodah** [bjodah/gsoc2017-bjodah#2]
- [ ] New disposition:
   - Improving sympy.codegen with more high-level abstractions
   - Support for different precisions
   - Optimizations

- [ ] Add "knowledge" input to `optimize.optimize` to leverage `Wild(..., exclude=[...])`.

- [ ] Look into leveraging `CodeBlock` cse functionality.

- [ ] Add a discussion about variable types and declarations (`Type`, `Variable`, `Pointer` & `Declaration`)

- [ ] Better motivating example for multiprecision

- [ ] Look into `sympy.strategies`

- [ ] Add a link to this repo in the proposal and mention that there is proof-of-concept code here.
